export default {
  success: true,
  data: {
    memes: [
      {
        id: "1",
        name: "Drake Hotline Bling",
        url: "https://i.imgflip.com/30blgx.jpg",
        width: 1200,
        height: 1200,
        box_count: 2,
      },
      {
        id: "2",
        name: "Drake Hotline Bling",
        url: "https://i.imgflip.com/30blgx.jpg",
        width: 1200,
        height: 1200,
        box_count: 2,
      },
      {
        id: "3",
        name: "Drake Hotline Bling",
        url: "https://i.imgflip.com/30blgx.jpg",
        width: 1200,
        height: 1200,
        box_count: 2,
      },
      {
        id: "4",
        name: "Drake Hotline Bling",
        url: "https://i.imgflip.com/30blgx.jpg",
        width: 1200,
        height: 1200,
        box_count: 2,
      },
      {
        id: "5",
        name: "Drake Hotline Bling",
        url: "https://i.imgflip.com/30blgx.jpg",
        width: 1200,
        height: 1200,
        box_count: 2,
      },
      {
        id: "6",
        name: "Drake Hotline Bling",
        url: "https://i.imgflip.com/30blgx.jpg",
        width: 1200,
        height: 1200,
        box_count: 2,
      },
    ],
  },
};
